version: '3.8'
services:
  db:
    image: postgres:15
    container_name: smart-bill-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: smart-bill
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - '5433:5432'
volumes:
  db_data:
    name: organize-simple-data
